export const adminMenuGroups = [
    {
        key: 'dashboard',
        label: 'Início',
        icon: 'LayoutDashboard',
        links: [
            {
                key: 'admin-dashboard',
                label: 'Visão geral',
                route: 'admin.home',
                match: ['admin.home'],
                icon: 'ChartNoAxesCombined',
            },
        ],
    },
    {
        key: 'cadastros',
        label: 'Cadastros',
        icon: 'Package',
        module: 'commercial',
        niches: ['commercial'],
        links: [
            {
                key: 'admin-products',
                label: 'Produtos',
                route: 'admin.products.index',
                match: ['admin.products.*'],
                icon: 'Box',
                module: 'catalog',
            },
            {
                key: 'admin-categories',
                label: 'Categorias',
                route: 'admin.categories.index',
                match: ['admin.categories.*'],
                icon: 'Tags',
                module: 'catalog',
            },
            {
                key: 'admin-clients',
                label: 'Clientes',
                route: 'admin.clients.index',
                match: ['admin.clients.*'],
                icon: 'Users2',
                module: ['crm', 'orders', 'pdv'],
            },
            {
                key: 'admin-suppliers',
                label: 'Fornecedores',
                route: 'admin.suppliers.index',
                match: ['admin.suppliers.*'],
                icon: 'Store',
                module: 'inventory',
            },
        ],
    },
    {
        key: 'operacao',
        label: 'Vendas e estoque',
        icon: 'ClipboardList',
        module: 'commercial',
        niches: ['commercial'],
        links: [
            {
                key: 'admin-pdv',
                label: 'PDV',
                route: 'admin.pdv.index',
                match: ['admin.pdv.*'],
                icon: 'ReceiptText',
                module: 'pdv',
            },
            {
                key: 'admin-orders',
                label: 'Pedidos',
                route: 'admin.orders.index',
                match: ['admin.orders.*'],
                icon: 'ShoppingBag',
                module: 'orders',
            },
            {
                key: 'admin-sales',
                label: 'Vendas',
                route: 'admin.sales.index',
                match: ['admin.sales.*'],
                icon: 'ReceiptText',
                module: 'pdv',
            },
            {
                key: 'admin-inventory',
                label: 'Estoque',
                route: 'admin.inventory.index',
                match: ['admin.inventory.*'],
                icon: 'Boxes',
                module: 'inventory',
            },
        ],
    },
    {
        key: 'financeiro',
        label: 'Financeiro',
        icon: 'CircleDollarSign',
        module: 'finance',
        niches: ['commercial'],
        links: [
            {
                key: 'admin-finance',
                label: 'Contas',
                route: 'admin.finance.index',
                match: ['admin.finance.index', 'admin.finance.payables', 'admin.finance.receivables', 'admin.finance.entries.*'],
                icon: 'Banknote',
                module: 'finance',
            },
            {
                key: 'admin-finance-payments',
                label: 'Pagamentos',
                route: 'admin.finance.payments',
                match: ['admin.finance.payments', 'admin.finance.gateways.*', 'admin.finance.methods.*'],
                icon: 'CreditCard',
                module: 'finance',
            },
        ],
    },
    {
        key: 'administrativo',
        label: 'Administrativo',
        icon: 'Building2',
        module: 'reports',
        links: [
            {
                key: 'admin-reports',
                label: 'Relatórios',
                route: 'admin.reports.index',
                match: ['admin.reports.*'],
                icon: 'FileText',
                module: 'reports',
            },
        ],
    },
    {
        key: 'auditoria',
        label: 'Auditoria',
        icon: 'History',
        links: [
            {
                key: 'admin-audit-accesses',
                label: 'Acessos',
                route: 'admin.audit.accesses',
                match: ['admin.audit.accesses'],
                icon: 'Clock3',
            },
        ],
    },
    {
        key: 'services-cadastros',
        label: 'Cadastros',
        icon: 'Package',
        module: 'services',
        niches: ['services'],
        links: [
            {
                key: 'admin-services-clients',
                label: 'Clientes',
                route: 'admin.clients.index',
                match: ['admin.clients.*'],
                icon: 'Users2',
                module: 'services',
            },
            {
                key: 'admin-services-categories',
                label: 'Categorias',
                route: 'admin.services.categories',
                match: ['admin.services.categories', 'admin.services.categories.*'],
                icon: 'Tags',
                module: 'services_catalog',
            },
            {
                key: 'admin-services-catalog',
                label: 'Catálogo',
                route: 'admin.services.catalog',
                match: ['admin.services.catalog'],
                icon: 'FileText',
                module: 'services_catalog',
            },
            {
                key: 'admin-services-suppliers',
                label: 'Fornecedores',
                route: 'admin.suppliers.index',
                match: ['admin.suppliers.*'],
                icon: 'Store',
                module: 'inventory',
            },
        ],
    },
    {
        key: 'services-operacao',
        label: 'Operação',
        icon: 'ClipboardList',
        module: 'services',
        niches: ['services'],
        links: [
            {
                key: 'admin-services-orders',
                label: 'Pedidos',
                route: 'admin.services.orders',
                match: ['admin.services.orders'],
                icon: 'CircleCheckBig',
                module: 'service_orders',
            },
            {
                key: 'admin-services-schedule',
                label: 'Agenda',
                route: 'admin.services.schedule',
                match: ['admin.services.schedule'],
                icon: 'CalendarClock',
                module: 'schedule',
                params: { layout: 'month' },
            },
        ],
    },
    {
        key: 'services-financeiro',
        label: 'Financeiro',
        icon: 'CircleDollarSign',
        module: 'services',
        niches: ['services'],
        links: [
            {
                key: 'admin-services-finance',
                label: 'Contas',
                route: 'admin.finance.index',
                match: ['admin.finance.index', 'admin.finance.payables', 'admin.finance.receivables', 'admin.finance.entries.*'],
                icon: 'Banknote',
                module: 'finance',
            },
            {
                key: 'admin-services-accounting',
                label: 'Gestão Contábil',
                route: 'admin.services.accounting',
                match: ['admin.services.accounting', 'admin.services.accounting.*'],
                icon: 'BookOpenCheck',
                module: 'tasks',
                businessTypes: ['accounting'],
            },
        ],
    },
    {
        key: 'configuracoes',
        label: 'Configurações',
        icon: 'Cog',
        links: [
            {
                key: 'admin-storefront',
                label: 'Loja virtual',
                route: 'admin.storefront.index',
                match: ['admin.storefront.*'],
                icon: 'Store',
                module: ['checkout', 'services_storefront'],
            },
            {
                key: 'admin-branding',
                label: 'Branding',
                route: 'admin.branding.index',
                match: ['admin.branding.*'],
                icon: 'Palette',
                module: 'files',
            },
        ],
    },
    {
        key: 'manuais',
        label: 'Manuais',
        icon: 'BookOpen',
        links: [
            {
                key: 'admin-manuals',
                label: 'Central de manuais',
                route: 'admin.manuals.index',
                match: ['admin.manuals.*'],
                icon: 'BookOpenCheck',
            },
        ],
    },
];
