export const adminMenuGroups = [
    {
        key: 'dashboard',
        label: 'Início',
        icon: 'LayoutDashboard',
        links: [
            {
                key: 'admin-dashboard',
                label: 'Visão geral',
                route: 'admin.home',
                match: ['admin.home'],
                icon: 'ChartNoAxesCombined',
            },
        ],
    },
    {
        key: 'cadastros',
        label: 'Cadastros',
        icon: 'Package',
        module: 'commercial',
        links: [
            {
                key: 'admin-products',
                label: 'Produtos',
                route: 'admin.products.index',
                match: ['admin.products.*'],
                icon: 'Box',
            },
            {
                key: 'admin-categories',
                label: 'Categorias',
                route: 'admin.categories.index',
                match: ['admin.categories.*'],
                icon: 'Tags',
            },
            {
                key: 'admin-clients',
                label: 'Clientes',
                route: 'admin.clients.index',
                match: ['admin.clients.*'],
                icon: 'Users2',
            },
            {
                key: 'admin-suppliers',
                label: 'Fornecedores',
                route: 'admin.suppliers.index',
                match: ['admin.suppliers.*'],
                icon: 'Store',
            },
        ],
    },
    {
        key: 'operacao',
        label: 'Vendas e estoque',
        icon: 'ClipboardList',
        module: 'commercial',
        links: [
            {
                key: 'admin-pdv',
                label: 'PDV',
                route: 'admin.pdv.index',
                match: ['admin.pdv.*'],
                icon: 'ReceiptText',
            },
            {
                key: 'admin-orders',
                label: 'Pedidos',
                route: 'admin.orders.index',
                match: ['admin.orders.*'],
                icon: 'ShoppingBag',
            },
            {
                key: 'admin-inventory',
                label: 'Estoque',
                route: 'admin.inventory.index',
                match: ['admin.inventory.*'],
                icon: 'Boxes',
            },
        ],
    },
    {
        key: 'financeiro',
        label: 'Financeiro',
        icon: 'CircleDollarSign',
        module: 'commercial',
        links: [
            {
                key: 'admin-finance',
                label: 'Contas',
                route: 'admin.finance.index',
                match: ['admin.finance.*'],
                icon: 'Banknote',
            },
        ],
    },
    {
        key: 'administrativo',
        label: 'Administrativo',
        icon: 'BookOpenCheck',
        module: 'commercial',
        links: [
            {
                key: 'admin-reports',
                label: 'Relatórios',
                route: 'admin.reports.index',
                match: ['admin.reports.*'],
                icon: 'FileText',
            },
        ],
    },
    {
        key: 'services',
        label: 'Serviços',
        icon: 'Briefcase',
        module: 'services',
        links: [
            {
                key: 'admin-services-overview',
                label: 'Visão geral',
                route: 'admin.services.index',
                match: ['admin.services.index'],
                icon: 'Clock3',
            },
            {
                key: 'admin-services-catalog',
                label: 'Catálogo',
                route: 'admin.services.catalog',
                match: ['admin.services.catalog'],
                icon: 'FileText',
            },
            {
                key: 'admin-services-orders',
                label: 'Pedidos',
                route: 'admin.services.orders',
                match: ['admin.services.orders'],
                icon: 'CircleCheckBig',
            },
            {
                key: 'admin-services-schedule',
                label: 'Agenda',
                route: 'admin.services.schedule',
                match: ['admin.services.schedule'],
                icon: 'CalendarClock',
            },
        ],
    },
    {
        key: 'configuracoes',
        label: 'Configurações',
        icon: 'Cog',
        links: [
            {
                key: 'admin-storefront',
                label: 'Loja virtual',
                route: 'admin.storefront.index',
                match: ['admin.storefront.*'],
                icon: 'Store',
            },
            {
                key: 'admin-branding',
                label: 'Branding',
                route: 'admin.branding.index',
                match: ['admin.branding.*'],
                icon: 'Palette',
            },
        ],
    },
];
